// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"GAME_DATE_EST")]
            public string GAME_DATE_EST { get; set; }

            [ColumnName(@"GAME_ID")]
            public float GAME_ID { get; set; }

            [ColumnName(@"GAME_STATUS_TEXT")]
            public string GAME_STATUS_TEXT { get; set; }

            [ColumnName(@"HOME_TEAM_ID")]
            public float HOME_TEAM_ID { get; set; }

            [ColumnName(@"VISITOR_TEAM_ID")]
            public float VISITOR_TEAM_ID { get; set; }

            [ColumnName(@"SEASON")]
            public float SEASON { get; set; }

            [ColumnName(@"TEAM_ID_home")]
            public float TEAM_ID_home { get; set; }

            [ColumnName(@"PTS_home")]
            public float PTS_home { get; set; }

            [ColumnName(@"FG_PCT_home")]
            public float FG_PCT_home { get; set; }

            [ColumnName(@"FT_PCT_home")]
            public float FT_PCT_home { get; set; }

            [ColumnName(@"FG3_PCT_home")]
            public float FG3_PCT_home { get; set; }

            [ColumnName(@"AST_home")]
            public float AST_home { get; set; }

            [ColumnName(@"REB_home")]
            public float REB_home { get; set; }

            [ColumnName(@"TEAM_ID_away")]
            public float TEAM_ID_away { get; set; }

            [ColumnName(@"PTS_away")]
            public float PTS_away { get; set; }

            [ColumnName(@"FG_PCT_away")]
            public float FG_PCT_away { get; set; }

            [ColumnName(@"FT_PCT_away")]
            public float FT_PCT_away { get; set; }

            [ColumnName(@"FG3_PCT_away")]
            public float FG3_PCT_away { get; set; }

            [ColumnName(@"AST_away")]
            public float AST_away { get; set; }

            [ColumnName(@"REB_away")]
            public float REB_away { get; set; }

            [ColumnName(@"HOME_TEAM_WINS")]
            public float HOME_TEAM_WINS { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
