﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"GAME_STATUS_TEXT", @"GAME_STATUS_TEXT")      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"HOME_TEAM_ID", @"HOME_TEAM_ID"),new InputOutputColumnPair(@"VISITOR_TEAM_ID", @"VISITOR_TEAM_ID"),new InputOutputColumnPair(@"SEASON", @"SEASON"),new InputOutputColumnPair(@"TEAM_ID_home", @"TEAM_ID_home"),new InputOutputColumnPair(@"PTS_home", @"PTS_home"),new InputOutputColumnPair(@"FG_PCT_home", @"FG_PCT_home"),new InputOutputColumnPair(@"FT_PCT_home", @"FT_PCT_home"),new InputOutputColumnPair(@"FG3_PCT_home", @"FG3_PCT_home"),new InputOutputColumnPair(@"AST_home", @"AST_home"),new InputOutputColumnPair(@"REB_home", @"REB_home"),new InputOutputColumnPair(@"TEAM_ID_away", @"TEAM_ID_away"),new InputOutputColumnPair(@"PTS_away", @"PTS_away"),new InputOutputColumnPair(@"FG_PCT_away", @"FG_PCT_away"),new InputOutputColumnPair(@"FT_PCT_away", @"FT_PCT_away"),new InputOutputColumnPair(@"FG3_PCT_away", @"FG3_PCT_away"),new InputOutputColumnPair(@"AST_away", @"AST_away"),new InputOutputColumnPair(@"REB_away", @"REB_away")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"GAME_DATE_EST", @"GAME_DATE_EST"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"GAME_STATUS_TEXT",@"HOME_TEAM_ID",@"VISITOR_TEAM_ID",@"SEASON",@"TEAM_ID_home",@"PTS_home",@"FG_PCT_home",@"FT_PCT_home",@"FG3_PCT_home",@"AST_home",@"REB_home",@"TEAM_ID_away",@"PTS_away",@"FG_PCT_away",@"FT_PCT_away",@"FG3_PCT_away",@"AST_away",@"REB_away",@"GAME_DATE_EST"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=8,MinimumExampleCountPerLeaf=31,NumberOfTrees=5,MaximumBinCountPerFeature=700,LearningRate=0.00213664890090002F,FeatureFraction=0.913097817403697F,LabelColumnName=@"HOME_TEAM_WINS",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
