
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace ML_Favorite_Console
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ML_Favorite.ModelInput sampleData = new ML_Favorite.ModelInput()
            {
                Schedule_date = @"9/2/1966",
                Schedule_season = 1966F,
                Schedule_week = 1F,
                Schedule_playoff = @"FALSE",
                Team_home = @"Miami Dolphins",
                Score_home = 14F,
                Score_away = 23F,
                Team_away = @"Oakland Raiders",
                Team_favorite_id = @"",
                Stadium = @"Orange Bowl",
                Stadium_neutral = @"FALSE",
                Weather_temperature = 83F,
                Weather_wind_mph = 6F,
                Weather_humidity = 71F,
                Weather_detail = @"",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ML_Favorite.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Over_under_line with predicted Over_under_line from sample data...\n\n");


            Console.WriteLine($"Schedule_date: {@"9/2/1966"}");
            Console.WriteLine($"Schedule_season: {1966F}");
            Console.WriteLine($"Schedule_week: {1F}");
            Console.WriteLine($"Schedule_playoff: {@"FALSE"}");
            Console.WriteLine($"Team_home: {@"Miami Dolphins"}");
            Console.WriteLine($"Score_home: {14F}");
            Console.WriteLine($"Score_away: {23F}");
            Console.WriteLine($"Team_away: {@"Oakland Raiders"}");
            Console.WriteLine($"Team_favorite_id: {@""}");
            Console.WriteLine($"Stadium: {@"Orange Bowl"}");
            Console.WriteLine($"Stadium_neutral: {@"FALSE"}");
            Console.WriteLine($"Weather_temperature: {83F}");
            Console.WriteLine($"Weather_wind_mph: {6F}");
            Console.WriteLine($"Weather_humidity: {71F}");
            Console.WriteLine($"Weather_detail: {@""}");


            Console.WriteLine($"\n\nPredicted Over_under_line: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
